### ISSUE TITLE
File path

### ISSUE THREAD

**Issue by jeffapderek** [MatthewHiggins2017/bioconda-PrimedRPA#1]
Hi,
Stumbling on the walk through here: after copying new parameters to file program doesn't recognise the file path for Step 3.
Have re-started terminal, restarted machine and checked all file paths within the Parameters file.
Any ideas please?

(base) jeff@UBU-CND7483XVZ:~$ cd ./Walk_Through_RPA_Primers/
(base) jeff@UBU-CND7483XVZ:~/Walk_Through_RPA_Primers$ ls -l
total 1704
-rw-r--r-- 1 jeff jeff    7478 May 15  2015 GCF_000896435.1_ViralProj76727_genomic.fna
-rw-r--r-- 1 jeff jeff   94163 May 19 12:06 HPV_Run_1_Alignment_Summary.csv
-rw-r--r-- 1 jeff jeff  237945 May 19 12:06 HPV_Run_1_Output_Sets.csv
-rw-r--r-- 1 jeff jeff 1393632 May 19 12:06 HPV_Run_1_PrimedRPA_Oligo_Binding_Sites.csv
-rw-r--r-- 1 jeff jeff    2378 May 19 12:16 PrimedRPA_Parameters.txt
(base) jeff@UBU-CND7483XVZ:~/Walk_Through_RPA_Primers$ PrimedRPA PrimedRPA_Parameters.txt

-------------------------------------------
----------------PrimedRPA------------------
-----Finding RPA Primer and Probe Sets-----
-------------Higgins M et al.--------------
-------------------------------------------

Parameters File Could Not Be Opened
Check File Path.
PLease run PrimedRPA --help to see valid options

**Comment by MatthewHiggins2017** [comment]
Hi Jeff,

First could you please double check the PrimedRPA_Parameters.txt file contains all 22, greater than symbols '>' as if there are more or less, this could trigger the error.  This could be done with the following command: grep '>' PrimedRPA_Parameters.txt | wc -l

Alternatively, if this doesnt work, could you please try the command-line option by running the following command:

PrimedRPA --RunID Debug --InputFile GCF_000896435.1_ViralProj76727_genomic.fna

**Comment by MatthewHiggins2017** [comment]
Hi Jeff,

Did this solution work?

Kind regards,
Matt.

**Comment by jeffapderek** [comment]
Hi Matt, thanks for the suggestion. Haven't had a chance today sorry. Will let you know asap
Many Thanks,Jeff

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by jeffapderek** [comment]
Hi Matt, yeah, that seems to have worked thanks:
22 '>'s and your files produced three debug_...csv files, with less oligo binding sites than the first.

Now for step 3 and it's produced a folder with blast inputs and outputs, but come up with an error message saying it can't find the 
ileNotFoundError: [Errno 2] No such file or directory: 'Adv_TAAGACCGCCTTCGGTCTATAAATTCACAGAG_AF082339.1.fa'

Any suggestions?
Many Thanks, Jeff

**Comment by jeffapderek** [comment]
Hi Matt,

Got round to having a go with my own data today. Fine when I'm just producing primers, probes and self-annealing scores, but getting an error when I attempat a cross-reactivity file. Have checked file paths, formatting trimmed sequences to equal length. Seems to be an error with the Blast search of the non-target sequences. Any suggestions please?
Error message when running from scratch i.e. without providing a previously generated alignment File/Binding sites:

Generating Alignment Summary (fine!)
Generating Primer/Probe Binding Site DataFrame
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/jeff/miniconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/jeff/miniconda3/lib/python3.7/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/jeff/miniconda3/bin/PrimedRPA", line 541, in IndentifyingAndFilteringOligos
    MaxBackgroundScoreBindingScore, MaxScoreBackSeq, HardFailBool  = BlastnBackgroundCheck(NucleotideSeq, AllParameter)
  File "/home/jeff/miniconda3/bin/PrimedRPA", line 195, in BlastnBackgroundCheck
    fastadict = FastaToDict('Adv_{}_{}.fa'.format(seq,CleanRefID))
  File "/home/jeff/miniconda3/bin/PrimedRPA", line 32, in FastaToDict
    with open(InputFile) as file_one:
FileNotFoundError: [Errno 2] No such file or directory: 'Adv_GTTGAATATTTACTTTAGATCATAAGCGGGTTGG_AB597287.1.fa'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jeff/miniconda3/bin/PrimedRPA", line 1034, in <module>
    CheckingAlignedOutputFile(AllParameter)
  File "/home/jeff/miniconda3/bin/PrimedRPA", line 810, in CheckingAlignedOutputFile
    PotentialPrimerProbeOut = pool.starmap(IndentifyingAndFilteringOligos,PrimerProbeCheckParallelInput)
  File "/home/jeff/miniconda3/lib/python3.7/multiprocessing/pool.py", line 276, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/home/jeff/miniconda3/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: 'Adv_GTTGAATATTTACTTTAGATCATAAGCGGGTTGG_AB597287.1.fa'

--
Much appreciated, Jeff

**Comment by MatthewHiggins2017** [comment]
Hi Jeff,

Apologies for the delay in my response and can you please check the version of samtools have installed with bioconda is v1.9 or higher

**Comment by jeffapderek** [comment]
Many thanks Matt. Did that via
conda update samtools 
and it's upgraded from v1.3.1 to 1.9, but still the same error message.

Let me know if you'd like me to run anything and let you know the error output

Jeff

**Comment by jeffapderek** [comment]
Hi Matt,

Have you had a chance to take a look at this please?

Cheers, Jeff

**Comment by vinay7623** [comment]
Had a similar problem installed samtools and updated it and the program works
