### ISSUE TITLE
Index Error: list index out of range

### ISSUE THREAD

**Issue by JamesGerardMann** [MatthewHiggins2017/bioconda-PrimedRPA#3]
I've come across this error when trying to run the program as well.

Traceback (most recent call last):
  File "/home/jmann/anaconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/jmann/anaconda3/lib/python3.7/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/jmann/anaconda3/bin/PrimedRPA", line 541, in IndentifyingAndFilteringOligos
    MaxBackgroundScoreBindingScore, MaxScoreBackSeq, HardFailBool  = BlastnBackgroundCheck(NucleotideSeq, AllParameter)
  File "/home/jmann/anaconda3/bin/PrimedRPA", line 203, in BlastnBackgroundCheck
    BackgroundMaxBindingPercentage, BackgroundMaxBindingString, BackgroundHardFail, BackgroundString = SSIdentification(seq, ComplementSeq, False, ShorterBackground)
  File "/home/jmann/anaconda3/bin/PrimedRPA", line 324, in SSIdentification
    if NucDict[DyanimicSeqList[StringPos]] == FixedSeqList[StringPos]:
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jmann/anaconda3/bin/PrimedRPA", line 1034, in <module>
    CheckingAlignedOutputFile(AllParameter)
  File "/home/jmann/anaconda3/bin/PrimedRPA", line 810, in CheckingAlignedOutputFile
    PotentialPrimerProbeOut = pool.starmap(IndentifyingAndFilteringOligos,PrimerProbeCheckParallelInput)
  File "/home/jmann/anaconda3/lib/python3.7/multiprocessing/pool.py", line 276, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/home/jmann/anaconda3/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
IndexError: list index out of range

**Comment by JamesGerardMann** [comment]
This only seems to happen when my blast_db.fasta exceeds 3500 sequences.

**Comment by MatthewHiggins2017** [comment]
Dear James,

I apologies for my slow response and this bug should be fixed in PrimedRPA v1.0.2 now available through bioconda.

**Comment by JamesGerardMann** [comment]
Thanks!
