### ISSUE TITLE
Error in running PrimedRPA

### ISSUE THREAD

**Issue by arm290** [MatthewHiggins2017/bioconda-PrimedRPA#5]
Hello! I wanted to reach out to see if there was any way I could get help in figuring out the solution to an issue that I am having in being able to run PrimedRPA. I followed the basic steps of installing conda, as well as creating an environment specifically for PrimedRPA. However, when I execute the program using the files to validate my installation, this string of errors is continually returned to the terminal:

`-------------------------------------------
----------------PrimedRPA------------------
-----Finding RPA Primer and Probe Sets-----
-------------Higgins M et al.--------------
-------------------------------------------

Generating Alignment Summary
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/inletant/miniconda3/envs/RPAenv/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/inletant/miniconda3/envs/RPAenv/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/inletant/miniconda3/envs/RPAenv/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/inletant/miniconda3/envs/RPAenv/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
  File "/Users/inletant/miniconda3/envs/RPAenv/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    main_content = runpy.run_path(main_path,
  File "/Users/inletant/miniconda3/envs/RPAenv/lib/python3.8/runpy.py", line 265, in run_path
    exitcode = _main(fd, parent_sentinel)
  File "/Users/inletant/miniconda3/envs/RPAenv/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/inletant/miniconda3/envs/RPAenv/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/inletant/miniconda3/envs/RPAenv/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/inletant/miniconda3/envs/RPAenv/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
    return _run_module_code(code, init_globals, run_name,
  File "/Users/inletant/miniconda3/envs/RPAenv/lib/python3.8/runpy.py", line 97, in _run_module_code
  File "/Users/inletant/miniconda3/envs/RPAenv/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/inletant/miniconda3/envs/RPAenv/lib/python3.8/runpy.py", line 87, in _run_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/inletant/miniconda3/envs/RPAenv/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/inletant/miniconda3/envs/RPAenv/bin/PrimedRPA", line 1046, in <module>
    exec(code, run_globals)
  File "/Users/inletant/miniconda3/envs/RPAenv/bin/PrimedRPA", line 1046, in <module>
    CheckingAlignedOutputFile(AllParameter)
  File "/Users/inletant/miniconda3/envs/RPAenv/bin/PrimedRPA", line 807, in CheckingAlignedOutputFile
    CheckingAlignedOutputFile(AllParameter)
  File "/Users/inletant/miniconda3/envs/RPAenv/bin/PrimedRPA", line 807, in CheckingAlignedOutputFile
    MergedAlignedDF = pd.concat(AlignedDFMultiThreadOupt).reset_index().drop(['index'],axis=1)
UnboundLocalError: local variable 'AlignedDFMultiThreadOupt' referenced before assignment
    MergedAlignedDF = pd.concat(AlignedDFMultiThreadOupt).reset_index().drop(['index'],axis=1)
UnboundLocalError: local variable 'AlignedDFMultiThreadOupt' referenced before assignment`

I'm not sure exactly whats going on, and truth be told I have only basic experience in utilizing Python and I have tried to reinstall miniconda, bioconda, and PrimedRPA a few times. Any help would be greatly appreciated, and thank you in advance!

**Comment by JamesGerardMann** [comment]
I've not used miniconda. Have you tried using full Anaconda?
https://www.digitalocean.com/community/tutorials/how-to-install-anaconda-on-ubuntu-18-04-quickstart

**Comment by arm290** [comment]
I have not tried installing the program using full Anaconda. It also seems that when I use the base miniconda environment with PrimedRPA installed, everything works fine! I believe that it has to do with the environment that I created for PrimedRPA not using the correct version of Python.

**Comment by xuzhiheng001** [comment]
Hi, I tried to install the primedRPA recently but it kept showing the unsaitisfiable error: the following specification was found to be incompatible with each other: Output in format: Request package -> available versions.  I use Python3.8, miniconda, bioconda and set the environment. Can you please let me know what is your python version and is there other tips for installing the primedPRA? This is my first time to use bioconda. Any suggestion will be helpful.

**Comment by zhaorongsong** [comment]
> I've not used miniconda. Have you tried using full Anaconda?
> https://www.digitalocean.com/community/tutorials/how-to-install-anaconda-on-ubuntu-18-04-quickstart

Hi, I used Anaconda, but I met the same mistake.
