### ISSUE TITLE
UnboundLocalError

### ISSUE THREAD

**Issue by thawatchai-chi** [MatthewHiggins2017/bioconda-PrimedRPA#7]
Hi, while I was following the step-by-step walkthrough, I encountered the following error:

Generating Alignment Summary
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/Benz/opt/miniconda3/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/Benz/opt/miniconda3/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/Benz/opt/miniconda3/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/Benz/opt/miniconda3/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/Benz/opt/miniconda3/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/Benz/opt/miniconda3/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/Benz/opt/miniconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/Benz/opt/miniconda3/bin/PrimedRPA", line 1046, in <module>
    CheckingAlignedOutputFile(AllParameter)
  File "/Users/Benz/opt/miniconda3/bin/PrimedRPA", line 807, in CheckingAlignedOutputFile
    MergedAlignedDF = pd.concat(AlignedDFMultiThreadOupt).reset_index().drop(['index'],axis=1)
UnboundLocalError: local variable 'AlignedDFMultiThreadOupt' referenced before assignment

     I already made sure that I installed the latest version of all dependencies (including samtools) and have tried full anaconda, mini anaconda, and using virtual environment. Does anyone have an idea where I might have gone wrong? Thank you in advance.

**Comment by eandrusz** [comment]
I have the same error! 

Generating Alignment Summary
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/elizabethandruszkiewicz/opt/anaconda2/envs/primed_env/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/elizabethandruszkiewicz/opt/anaconda2/envs/primed_env/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/elizabethandruszkiewicz/opt/anaconda2/envs/primed_env/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/elizabethandruszkiewicz/opt/anaconda2/envs/primed_env/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/elizabethandruszkiewicz/opt/anaconda2/envs/primed_env/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/elizabethandruszkiewicz/opt/anaconda2/envs/primed_env/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/elizabethandruszkiewicz/opt/anaconda2/envs/primed_env/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/elizabethandruszkiewicz/opt/anaconda2/envs/primed_env/bin/PrimedRPA", line 1046, in <module>
    CheckingAlignedOutputFile(AllParameter)
  File "/Users/elizabethandruszkiewicz/opt/anaconda2/envs/primed_env/bin/PrimedRPA", line 807, in CheckingAlignedOutputFile
    MergedAlignedDF = pd.concat(AlignedDFMultiThreadOupt).reset_index().drop(['index'],axis=1)
UnboundLocalError: local variable 'AlignedDFMultiThreadOupt' referenced before assignment

**Comment by na-89** [comment]
I also encountered the same problem, have you solved your problem?

**Comment by thawatchai-chi** [comment]
Hey,
   I solved the problem by downgrading the Python. I forgot which version I downgraded it to (haven’t used it for a while), but I’ll take a look and let you know.

Cheers,
Benz

**Comment by na-89** [comment]
Hi，Benz:
    Thanks for the reply, I use the 3.6 version of python, it seems to be able to run successfully ！

Best regards!
Nana
